### ISSUE TITLE
App installtion

### ISSUE THREAD

**Issue by srinivasgupshup** [inspireui/mstore#145]
Hi Team,

We are panning to buy app if we are not able to configure do u charge for installation. if we buy Regular licence is for life time right $59 is one time cost right...

**Comment by inspireui** [comment]
Please help to view more detail about the licence from - https://codecanyon.net/licenses/standard?license=regular

You will get life time update for 59$, but please note that one regular licence only use for one end product app which use to delivery to Appstore & Google Play.

We have supported installing services but so far our time is full of capacity so that we could not handle more ticket

Thank you,
InspireUI
