### ISSUE TITLE
woocommerce_rest_authentication_error

### ISSUE THREAD

**Issue by z5614036** [inspireui/mstore#159]
{"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}，I have changed consumerKey and consumerSecret for app.

**Comment by z5614036** [comment]
http://192.168.1.107:8888/wordpress/wp-json/wc/v2/products?oauth_consumer_key=ck_2cd037d426254baefcdb4fc164181bb54ce2e155&oauth_nonce=7mKZf1jPHTh1nTRbTmrfZQvTxs5Yo5t0&oauth_signature_method=H
MAC-SHA256&oauth_timestamp=1519549096&oauth_version=1.0&per_page=10&page=1&purchasable=true&category=18&oauth_signature=H8%2BCWrX80z36uxdkvtv6RBkJGNh8IJRxZrDzWb5gSfw%3D,and 
method: 'GET',  encoding: 'utf8', timeout: 10,qs:{ oauth_consumer_key: 'ck_2cd037d426254baefcdb4fc164181bb54ce2e155', oauth_nonce:'hPYN1Ktxp1opWWGBy8xry8HQIeYMCyVL',
oauth_signature_method: 'HMAC-SHA256',oauth_timestamp: 1519549096,oauth_version: '1.0',per_page: 10,page: 1, purchasable: true,category: 21,oauth_signature: 'RR61%2F0DKD3ew8AFRLJewyJ5GqWBQ%2FzanIWzCZg3p8xA%3D' },headers: { 'Cache-Control': 'no-cache' } }

**Comment by z5614036** [comment]
![picture](https://user-images.githubusercontent.com/24545834/36639792-e952bf0c-1a4e-11e8-8ec8-d5f748e68abd.jpg)

**Comment by stmkjp** [comment]
@z5614036 , I think it's due to the plain http connection. 
I had the same problem but it's gone after I made a https connection.

It would be no problem if you connect the server through https.but otherwise, you have to change the app code a little bit. ( But I recommend to implement https connection )

Please refer here for implementing http connection => https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

**Comment by inspireui** [comment]
@z5614036 could you try to change to vhost with port 80 instead of current setting

Also check Setting/Permalink Settings/ Change to "Post name
