### ISSUE TITLE
Errors in my app

### ISSUE THREAD

**Issue by luisalexhg** [inspireui/mstore#85]
I have a little problem, I install the demo and all is perfect, but when I connect app to my website, some functions don’t work, for example when I login, the page don’t redirect, or when I confirm order, the page don’t load, pls assistance.

I install all the plugins and activations
![captura de pantalla 2017-11-25 a las 13 48 29](https://user-images.githubusercontent.com/28818275/33233659-6507d32c-d1e7-11e7-9a6b-c185ebec935f.png)
![captura de pantalla 2017-11-25 a las 13 48 35](https://user-images.githubusercontent.com/28818275/33233660-6659cbea-d1e7-11e7-81f3-44b8c627b497.png)
![captura de pantalla 2017-11-25 a las 13 48 47](https://user-images.githubusercontent.com/28818275/33233661-68118ce8-d1e7-11e7-8440-d61729c7c45b.png)

Products image don't load:
![captura de pantalla 2017-11-25 a las 13 41 45](https://user-images.githubusercontent.com/28818275/33233589-6520301c-d1e6-11e7-94b8-0ee764e4b919.png)

Products image don't load and can't delete product from the cart
![captura de pantalla 2017-11-25 a las 13 42 26](https://user-images.githubusercontent.com/28818275/33233600-858284fe-d1e6-11e7-85be-5c10c667c5be.png)

When I login the page continue loading, but I'm logged in
![captura de pantalla 2017-11-25 a las 13 44 32](https://user-images.githubusercontent.com/28818275/33233625-d60ad52a-d1e6-11e7-9a0f-1f05587a3706.png)
![captura de pantalla 2017-11-25 a las 13 44 48](https://user-images.githubusercontent.com/28818275/33233653-3b052f66-d1e7-11e7-87c5-78557fdb75db.png)

**Comment by inspireui** [comment]
Could you help to download the pre-config site form this repo - https://github.com/inspireui/mstore We have added some all config that worked with the app, then you can figure out the issues from your website. 

Please note the image issues could be fixed by update the layout.js config - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html. We are going to release new v3.4 which will help easy to config in one file. 

Thank you!

**Comment by inspireui** [comment]
Please update latest v3.4.2 for all fixed Thank you!
